### PR TITLE
Added a new theme with smaller fonts

### PR DESCRIPTION
**Pull request by KyriakosG78**

### CODE REVIEW

**Comment by armhil** [comment]
If this is identical to `Desert` with only difference being the font-size, I'll add the font-size as a feature. It looks like there's sufficient interest around that anyways :)

**Comment by KyriakosG78** [comment]
I tried to use the colors from the netbens with smaller fonts because every time I paste in the word I have to reduce the size of letters.

**Comment by armhil** [comment]
I've added this feature now, font size as well as a few different fonts. I'll work on updating the styles package so the fonts are exposed there and people continue updating it if they want to.

**Comment by armhil** [comment]
Closing this PR - as this feature is added to the default functionality. @KyriakosG78 - your PR is very much appreciated and I wouldn't mind getting more PRs from you : )

**Comment by KyriakosG78** [comment]
Perfect ! This is a better implementation than another theme with smaller fonts ! It works very well. See only that the font size, for example, if you set size 8 it turns out 6 or 12 it turns out 9.

**Pull request closed without merging**
